# Generated by Django 3.1.6 on 2022-04-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Prénom'),
        ),
    ]
