# Generated by Django 3.2.12 on 2022-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20220404_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
