# Generated by Django 3.2.12 on 2022-04-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20220413_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planning',
            options={'ordering': ('-created',)},
        ),
    ]
