# Generated by Django 5.0.6 on 2024-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
