# Generated by Django 3.2.12 on 2022-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0002_auto_20220404_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
