# Generated by Django 3.2.12 on 2022-04-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0003_activity_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_default',
        ),
        migrations.AddField(
            model_name='salle',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
