# Generated by Django 3.2.12 on 2022-04-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0005_alter_activity_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=models.CharField(blank=True, default='#233774', max_length=50, null=True),
        ),
    ]
