# Generated by Django 3.2.12 on 2022-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0006_alter_activity_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='door_ip',
            field=models.CharField(default='192.168.1.2', max_length=20, verbose_name='Adresse ip de la porte'),
            preserve_default=False,
        ),
    ]
