# Generated by Django 3.2.12 on 2022-07-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0007_salle_door_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.CharField(max_length=20, verbose_name='Adresse ip de la porte')),
                ('username', models.CharField(max_length=50, verbose_name='username de la porte')),
                ('password', models.CharField(max_length=30, verbose_name='password de la porte')),
            ],
        ),
        migrations.RemoveField(
            model_name='salle',
            name='door_ip',
        ),
        migrations.AddField(
            model_name='salle',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='salle_activite.door'),
        ),
    ]
