# Generated by Django 3.2.12 on 2023-03-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0009_auto_20230319_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='door',
            new_name='salle',
        ),
    ]
