# Generated by Django 5.0.6 on 2024-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0011_alter_activity_id_alter_door_id_alter_salle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='ip_adress',
            field=models.CharField(max_length=20, verbose_name='Adresse ip '),
        ),
        migrations.AlterField(
            model_name='door',
            name='password',
            field=models.CharField(max_length=30, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='door',
            name='username',
            field=models.CharField(max_length=50, verbose_name='username'),
        ),
    ]
