# Generated by Django 3.1.6 on 2022-04-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salle_activite', '0001_initial'),
        ('planning', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.TimeField()),
                ('hour_finish', models.TimeField()),
                ('day', models.CharField(choices=[('SA', 'Samedi'), ('DI', 'Dimanche'), ('LU', 'Lundi'), ('MA', 'Mardi'), ('ME', 'Mercredi'), ('JE', 'Jeudi'), ('VE', 'Vendredi')], default='DI', max_length=2, verbose_name='Jour')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='salle_activite.activity', verbose_name='activities')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='client.coach')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.planning')),
            ],
            options={
                'ordering': ['hour_start'],
            },
        ),
    ]
