# Generated by Django 5.0.6 on 2024-07-31 11:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('planning', '0001_initial'),
        ('salle_activite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.TimeField()),
                ('hour_finish', models.TimeField()),
                ('day', models.CharField(choices=[('SA', 'Samedi'), ('DI', 'Dimanche'), ('LU', 'Lundi'), ('MA', 'Mardi'), ('ME', 'Mercredi'), ('JE', 'Jeudi'), ('VE', 'Vendredi')], default='DI', max_length=2, verbose_name='Jour')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom du creneau')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='salle_activite.activity', verbose_name='activities')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='client.coach')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.planning')),
            ],
            options={
                'ordering': ['hour_start'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCreneau',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hour_start', models.TimeField()),
                ('hour_finish', models.TimeField()),
                ('day', models.CharField(choices=[('SA', 'Samedi'), ('DI', 'Dimanche'), ('LU', 'Lundi'), ('MA', 'Mardi'), ('ME', 'Mercredi'), ('JE', 'Jeudi'), ('VE', 'Vendredi')], default='DI', max_length=2, verbose_name='Jour')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom du creneau')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Date de dernière mise à jour')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salle_activite.activity', verbose_name='activities')),
                ('coach', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.coach')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('planning', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='planning.planning')),
            ],
            options={
                'verbose_name': 'historical creneau',
                'verbose_name_plural': 'historical creneaus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
