# Generated by Django 5.0.6 on 2024-12-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
