# Generated by Django 5.0.6 on 2025-11-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0002_delete_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCreneau',
        ),
    ]
