# Generated by Django 3.2.12 on 2022-04-10 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0002_alter_creneau_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='color',
            field=models.CharField(blank=True, default='#333333', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creneau',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de Création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creneau',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour'),
        ),
    ]
