# Generated by Django 5.0.6 on 2025-11-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0003_delete_historicalcreneau'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.planning'),
        ),
    ]
