# Generated by Django 3.2.12 on 2022-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0003_auto_20220410_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='day',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='nom du creneau'),
        ),
    ]
