# Generated by Django 5.0.6 on 2024-10-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0004_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
