# Generated by Django 3.2.12 on 2022-04-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0005_alter_creneau_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='name',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='nom du creneau'),
        ),
    ]
