# Generated by Django 3.2.12 on 2022-05-04 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0006_alter_activity_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0005_alter_planning_options'),
        ('client', '0009_historicalclient_historicalcoach_historicalpersonnel'),
        ('creneau', '0007_alter_creneau_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCreneau',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hour_start', models.TimeField()),
                ('hour_finish', models.TimeField()),
                ('day', models.CharField(choices=[('SA', 'Samedi'), ('DI', 'Dimanche'), ('LU', 'Lundi'), ('MA', 'Mardi'), ('ME', 'Mercredi'), ('JE', 'Jeudi'), ('VE', 'Vendredi')], default='DI', max_length=2, verbose_name='Jour')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom du creneau')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Date de dernière mise à jour')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salle_activite.activity', verbose_name='activities')),
                ('coach', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.coach')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('planning', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='planning.planning')),
            ],
            options={
                'verbose_name': 'historical creneau',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
