# Generated by Django 5.0.2 on 2024-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0008_historicalcreneau'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcreneau',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical creneau', 'verbose_name_plural': 'historical creneaus'},
        ),
        migrations.AlterField(
            model_name='historicalcreneau',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
