# Generated by Django 5.0.6 on 2024-12-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_alter_historicalpresence_date_alter_presence_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-created']},
        ),
    ]
