# Generated by Django 5.0.6 on 2024-12-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_alter_presence_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPresence',
        ),
    ]
