# Generated by Django 5.0.6 on 2025-11-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0004_delete_historicalpresence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPresenceCoach',
        ),
    ]
