# Generated by Django 3.2.12 on 2023-12-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0004_auto_20230327_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpresence',
            name='remote_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presence',
            name='remote_device',
            field=models.BooleanField(default=False),
        ),
    ]
