# Generated by Django 3.2.12 on 2023-12-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0005_auto_20231226_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpresence',
            name='remote_device',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='remote_device',
        ),
    ]
