# Generated by Django 5.0.2 on 2024-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0006_auto_20231226_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpresence',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical presence', 'verbose_name_plural': 'historical presences'},
        ),
        migrations.AlterModelOptions(
            name='historicalpresencecoach',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical presence coach', 'verbose_name_plural': 'historical presence coachs'},
        ),
        migrations.AlterField(
            model_name='historicalpresence',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpresencecoach',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
