# Generated by Django 5.0.6 on 2024-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0008_alter_historicalpresence_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpresencecoach',
            name='hour_entree',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presencecoach',
            name='hour_entree',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
