# Generated by Django 5.0.6 on 2024-07-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0014_alter_abonnementclient_blocking_date_and_more'),
        ('presence', '0009_alter_historicalpresencecoach_hour_entree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpresence',
            name='abc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='abonnement.abonnementclient', verbose_name='Abonnement client'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='abc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='abonnement.abonnementclient', verbose_name='Abonnement client'),
        ),
    ]
