# Generated by Django 5.0.6 on 2025-11-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_options_alter_coach_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalClient',
        ),
    ]
