# Generated by Django 5.0.6 on 2024-10-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_coach_id_alter_historicalcoach_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='date_added',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
