# Generated by Django 5.0.6 on 2024-10-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='date_added',
            field=models.DateField(blank=True, default=2024, editable=False),
            preserve_default=False,
        ),
    ]
