# Generated by Django 3.2.12 on 2022-04-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20220410_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='carte',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
