# Generated by Django 5.0.6 on 2025-11-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_delete_historicalclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpersonnel',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCoach',
        ),
        migrations.DeleteModel(
            name='HistoricalPersonnel',
        ),
    ]
