# Generated by Django 3.2.12 on 2022-04-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20220417_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-updated',)},
        ),
    ]
