# Generated by Django 3.2.12 on 2022-07-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_historicalclient_historicalcoach_historicalpersonnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hex_card',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='hex_card',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
