# Generated by Django 3.2.12 on 2023-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20220921_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_on_salle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='is_on_salle',
            field=models.BooleanField(default=False),
        ),
    ]
