# Generated by Django 5.0.2 on 2024-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20230313_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalclient',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical client', 'verbose_name_plural': 'historical clients'},
        ),
        migrations.AlterModelOptions(
            name='historicalcoach',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical coach', 'verbose_name_plural': 'historical coachs'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersonnel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical personnel', 'verbose_name_plural': 'historical personnels'},
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcoach',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpersonnel',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
