# Generated by Django 5.0.6 on 2024-07-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_client_last_name_alter_coach_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maladie',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
