# Generated by Django 5.0.6 on 2024-07-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_maladie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='maladies',
            field=models.ManyToManyField(blank=True, to='client.maladie'),
        ),
    ]
