# Generated by Django 5.0.6 on 2024-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_client_maladies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='pay_per_hour',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Salaire par heure'),
        ),
        migrations.AlterField(
            model_name='historicalcoach',
            name='pay_per_hour',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Salaire par heure'),
        ),
    ]
