# Generated by Django 5.0.6 on 2024-10-27 09:21

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salle_activite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('blocking_date', models.DateField(blank=True, null=True)),
                ('presence_quantity', models.IntegerField(blank=True, null=True)),
                ('reste', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Reste')),
                ('archiver', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAbonnementClient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('blocking_date', models.DateField(blank=True, null=True)),
                ('presence_quantity', models.IntegerField(blank=True, null=True)),
                ('reste', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Reste')),
                ('archiver', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(blank=True, editable=False)),
                ('updated_date_time', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical abonnement client',
                'verbose_name_plural': 'historical abonnement clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nom')),
                ('type_of', models.CharField(choices=[('VH', 'Volume Horaire'), ('AL', 'Accés Libre'), ('SF', 'Seances Fix'), ('SL', 'Seances Libre')], default='VH', max_length=2, verbose_name="type d'abonnement")),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='prix')),
                ('length', models.CharField(choices=[('1', '1 Jour'), ('15', '15 Jours'), ('45', '45 Jours'), ('30', '1 mois'), ('60', '2 mois'), ('90', '3 mois'), ('120', '4 mois'), ('150', '5 mois'), ('180', '6 mois')], max_length=8, verbose_name='Durée')),
                ('seances_quantity', models.IntegerField(blank=True, null=True, verbose_name='Nombre de séances/heureux')),
                ('actif', models.BooleanField(default=True)),
                ('salles', models.ManyToManyField(related_name='abonnements', to='salle_activite.salle')),
            ],
            options={
                'permissions': [('can_view_history', 'Can View history')],
            },
        ),
    ]
