# Generated by Django 3.1.6 on 2022-04-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creneau', '0001_initial'),
        ('salle_activite', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nom')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='prix')),
                ('number_of_days', models.IntegerField()),
                ('seances_quantity', models.IntegerField()),
                ('systeme_cochage', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('salles', models.ManyToManyField(related_name='abonnements', to='salle_activite.Salle')),
            ],
        ),
        migrations.CreateModel(
            name='AbonnementClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
                ('presence_quantity', models.IntegerField(blank=True, null=True)),
                ('reste', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='prix')),
                ('archiver', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement_client', to='client.client')),
                ('creneaux', models.ManyToManyField(blank=True, related_name='pizzas', to='creneau.Creneau', verbose_name='créneau')),
                ('type_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_abonnement_client', to='abonnement.abonnement')),
            ],
        ),
    ]
