# Generated by Django 3.2.12 on 2022-04-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0002_auto_20220404_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='type_of',
            field=models.CharField(choices=[('OU', 'Ouvert'), ('VH', 'Volume Horaire'), ('SL', 'Seance limité')], default='OU', max_length=2, verbose_name="type d'abonnement"),
        ),
    ]
