# Generated by Django 5.0.6 on 2024-12-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0003_delete_historicalabonnementclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='seances_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de séances/Heures'),
        ),
    ]
