# Generated by Django 5.0.6 on 2024-09-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0003_alter_abonnement_id_alter_abonnementclient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='length',
            field=models.CharField(choices=[('1 Jour', '1 Jour'), ('15 Jours', '15 Jours'), ('45 Jours', '45 Jours'), ('1 mois', '1 mois'), ('2 mois', '2 mois'), ('3 mois', '3 mois'), ('4 mois', '4 mois'), ('5 mois', '5 mois'), ('6 mois', '6 mois')], max_length=8, verbose_name='Durée'),
        ),
    ]
