# Generated by Django 3.2.12 on 2022-04-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0007_alter_creneau_name'),
        ('abonnement', '0004_auto_20220412_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='creneaux',
            field=models.ManyToManyField(blank=True, related_name='abonnements', to='creneau.Creneau', verbose_name='créneau'),
        ),
    ]
