# Generated by Django 5.0.6 on 2025-11-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0004_alter_abonnement_seances_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementclient',
            name='already_blocked',
            field=models.BooleanField(default=False, verbose_name='Déjà bloqué'),
        ),
    ]
