# Generated by Django 5.0.6 on 2024-10-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0004_alter_abonnement_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='length',
            field=models.CharField(choices=[('1', '1 Jour'), ('15', '15 Jours'), ('45', '45 Jours'), ('30', '1 mois'), ('60', '2 mois'), ('90', '3 mois'), ('120', '4 mois'), ('150', '5 mois'), ('180', '6 mois')], max_length=8, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='seances_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de séances/heureux'),
        ),
        migrations.AlterField(
            model_name='abonnementclient',
            name='reste',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Reste'),
        ),
        migrations.AlterField(
            model_name='historicalabonnementclient',
            name='reste',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Reste'),
        ),
    ]
