# Generated by Django 5.0.6 on 2025-11-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0005_abonnementclient_already_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonnementclient',
            old_name='blocking_date',
            new_name='lock_start_date',
        ),
        migrations.RemoveField(
            model_name='abonnementclient',
            name='already_blocked',
        ),
        migrations.AddField(
            model_name='abonnementclient',
            name='has_been_locked_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abonnementclient',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abonnementclient',
            name='lock_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BlockAbonnementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_date', models.DateField()),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
                ('abonnement_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_abonnement_client', to='abonnement.abonnementclient')),
            ],
        ),
    ]
