# Generated by Django 3.2.12 on 2022-04-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0006_auto_20220413_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='presence_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
