# Generated by Django 3.2.12 on 2022-04-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20220418_0001'),
        ('abonnement', '0007_alter_abonnementclient_presence_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnement_client', to='client.client'),
        ),
    ]
