# Generated by Django 3.2.12 on 2022-09-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0009_historicalabonnementclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonnement',
            options={'permissions': [('can_view_history', 'Can View history')]},
        ),
    ]
