# Generated by Django 3.2.12 on 2023-12-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0010_alter_abonnement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementclient',
            name='blocking_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalabonnementclient',
            name='blocking_date',
            field=models.DateField(null=True),
        ),
    ]
