# Generated by Django 5.0.2 on 2024-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0011_auto_20231224_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalabonnementclient',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical abonnement client', 'verbose_name_plural': 'historical abonnement clients'},
        ),
        migrations.AlterField(
            model_name='historicalabonnementclient',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
