# Generated by Django 5.0.6 on 2024-07-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0013_alter_abonnement_id_alter_abonnementclient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='blocking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalabonnementclient',
            name='blocking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
