# Generated by Django 5.0.6 on 2024-11-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-last_modified'], 'permissions': [('can_view_history', 'Can View history'), ('can_view_statistique', 'Can View Statistique')]},
        ),
    ]
