# Generated by Django 5.0.6 on 2024-12-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_paiement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('can_view_history', 'Can View history'), ('can_view_statistique', 'Can View Statistique')]},
        ),
    ]
