# Generated by Django 5.0.6 on 2025-11-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_paiement_options_alter_transaction_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalautre',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalautre',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalpaiement',
            name='abonnement_client',
        ),
        migrations.RemoveField(
            model_name='historicalpaiement',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpaiement',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalremuneration',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalremuneration',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='historicalremuneration',
            name='transaction_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalremunerationprof',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='historicalremunerationprof',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalremunerationprof',
            name='transaction_ptr',
        ),
        migrations.DeleteModel(
            name='HistoricalAssuranceTransaction',
        ),
        migrations.DeleteModel(
            name='HistoricalAutre',
        ),
        migrations.DeleteModel(
            name='HistoricalPaiement',
        ),
        migrations.DeleteModel(
            name='HistoricalRemuneration',
        ),
        migrations.DeleteModel(
            name='HistoricalRemunerationProf',
        ),
    ]
