# Generated by Django 5.0.2 on 2024-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalassurancetransaction',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical assurance transaction', 'verbose_name_plural': 'historical assurance transactions'},
        ),
        migrations.AlterModelOptions(
            name='historicalautre',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical autre', 'verbose_name_plural': 'historical autres'},
        ),
        migrations.AlterModelOptions(
            name='historicalpaiement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical paiement', 'verbose_name_plural': 'historical paiements'},
        ),
        migrations.AlterModelOptions(
            name='historicalremuneration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical remuneration', 'verbose_name_plural': 'historical remunerations'},
        ),
        migrations.AlterModelOptions(
            name='historicalremunerationprof',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical remuneration prof', 'verbose_name_plural': 'historical remuneration profs'},
        ),
        migrations.AlterField(
            model_name='historicalassurancetransaction',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalautre',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpaiement',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalremuneration',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalremunerationprof',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
